### PR TITLE
OSX drag issues. Fixes #74, #195, #191

### LINKED ISSUE #74: Drag & Drop From Application Non-Functional in OS/X / Chrome
To test this, pop open the demo in Chrome and head over to an OS/X application like iTunes.

Select one or more files (I am using 3 for the sake of testing) and drag them into the drop area. The hover event will fire, but `onDrop` never occurs and the files are never actually uploaded.

### PR DESCRIPTION
**Pull request by MaffooBristol**
#74 #195 #191

### CODE REVIEW

**Comment by MaffooBristol** [comment]
Any best practice for tests, @okonet?

Cheers

**Comment by MaffooBristol** [comment]
Weird:

```
61:5  error  Assignment to property of function parameter 'e'  no-param-reassign
```

Getting the feeling eslint has got a bit confused about this one?

**Comment by okonet** [comment]
Great!

You can skip the line with `eslint-disable-line`. 

Not sure how to test this either.

**Comment by MaffooBristol** [comment]
Okay, I tried it out myself and it doesn't work 😫 

I thought I would do the PR from the previous suggestion as I had assumed it would work, but it hasn't...

Back to the drawing board?

**Comment by MaffooBristol** [comment]
I lie! It does work, was my own stupidity ha.

**Comment by okonet** [comment]
@MaffooBristol can you fix the remaining ESLint error so I can merge it?

**Comment by MaffooBristol** [comment]
@okonet Done, should be building now.

**Comment by MaffooBristol** [comment]
Спасибо!

**Pull request merged**
