### PR TITLE
Fixed double `onClick` event on parent element

### PR DESCRIPTION
**Pull request by aaronbeall**
Fixes https://github.com/okonet/react-dropzone/issues/252

### CODE REVIEW

**Comment by okonet** [comment]
Thanks for the PR!

Two things before I'll merge it:

1. The build fails due to some eslint errors. Please fix those.
1. I think we'll need a test for this new code. It should cover the case you've described in #252. Can you please add it?

BTW please do `npm install` — it will install `lint-staged` that should prevent eslint-broken commits.

**Comment by aaronbeall** [comment]
I ran `npm install` and `npm build` and I don't see the errors... what do I need to run to see these errors?

**Comment by aaronbeall** [comment]
Ah I see it running `npm run eslint:src`

**Comment by okonet** [comment]
You should have seen these before commit. This project has an integrated pre-commit hook.

**Comment by aaronbeall** [comment]
I tried to add this test:

```
      const onClickSpy = spy();

      const component = TestUtils.renderIntoDocument(
        <div onClick={onClickSpy}>
          <Dropzone className="dropzone-content" />
        </div>
      );

      const content = TestUtils.findRenderedDOMComponentWithClass(component, 'dropzone-content');
      TestUtils.Simulate.click(content);
      expect(onClickSpy.callCount).to.equal(1);
```

However this gives me `Invariant Violation: findAllInRenderedTree(...): instance must be a composite component` apparently because [you can't use this with a DOM element](https://github.com/facebook/react/issues/4692).

So I tried this:

```
      const onClickSpy = spy();

      const WrappedDropzone = () => (
        <div onClick={onClickSpy}>
          <Dropzone className="dropzone-content" />
        </div>
      );

      const component = TestUtils.renderIntoDocument(
        <WrappedDropzone />
      );

      const content = TestUtils.findRenderedDOMComponentWithClass(component, 'dropzone-content');
      TestUtils.Simulate.click(content);
      expect(onClickSpy.callCount).to.equal(1);
```

Which throws: `Error: Did not find exactly one match (found: 0) for class:dropzone-content`. 

Any tips?

**Comment by aaronbeall** [comment]
Yes I should have seen the ESLint pre-commit errors but I edited it straight on Github after messing around with things locally... which was silly. :)

**Comment by okonet** [comment]
@aaronbeall any updates on this PR? Do you think you will be able to add tests for this case?

**Comment by aaronbeall** [comment]
I got stuck on that test in my last reply and haven't been able to circle back to figure out how to workaround the `TestUtils` limitation... my quick research made it sound like you aren't expected to test a wrapping element with `TestUtils`. 😖

**Comment by okonet** [comment]
> my quick research made it sound like you aren't expected to test a wrapping element with TestUtils

I'm not sure what you mean by that. Can you elaborate please?

**Comment by aaronbeall** [comment]
This: https://github.com/facebook/react/issues/4692

I'm not sure that's the issue but that was as far as I got...

**Comment by okonet** [comment]
@aaronbeall I was able to repro the case in tests: https://github.com/okonet/react-dropzone/pull/309/files#diff-3d2fceb7429c5721d178682a76d75809R514

I'm skipping the test for now but it is probably a good idea to move it to this branch and land as a part of this PR. Let me finish my work and let's update this one.

**Comment by okonet** [comment]
This turned out to be a bit trickier and required me to add `onClick` callback support so I'm fixing this in #312. Thanks for pointing out and your effort!

**Pull request closed without merging**
