### PR TITLE
If accept prop is specified, enforce it on drop

### LINKED ISSUE #138: onDrop is being called with files that shouldn't be accepted
IMO, if the file isn't accepted, it shouldn't be sent to the onDrop method

dnd

### LINKED ISSUE #145: Accpets files dropped of the wrong MIME type?
The CSS changes to red but if a different file is dropped on it it still accepts it?

### PR DESCRIPTION
**Pull request by tmarshall**
closes #138
closes #145

### CODE REVIEW

**Comment by okonet** [comment]
Hey!thanks for the PR! Looking good. 

I noticed you changed the logic a bit that isn't covered with tests. Do you mind adding tests for cases when `accepts` isn't specified? If they will be green, I'm good to merge this. 

I'm also wondering if this one will require a major version bump because of this change. What do you think?

**Comment by tmarshall** [comment]
> I'm also wondering if this one will require a major version bump because of this change. What do you think?

Seems like a patch to me, since it is resolving an interaction, as to how the developers expect it to happen. Though it depends on your perspective

**Comment by tmarshall** [comment]
@okonet test added

**Comment by okonet** [comment]
Yes but isn't it a breaking change? I mean for those who are relying on a wrong behavior it will break stuff.

**Comment by tmarshall** [comment]
@okonet from that perspective yes :)

**Comment by alexeygolev** [comment]
Any progress on merging this?

**Comment by okonet** [comment]
I'll release a patch version

**Comment by hank7444** [comment]
ok, I found the issue, `onDrop is now called only if all files are passing the accept`,
I commented my accept and it worked

**Comment by hank7444** [comment]
my accept is java .jar file, it not works :(

accept="application/java-archive"

**Comment by okonet** [comment]
I'm not sure `application/java-archive` is a valid parameter. See the spec: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#Attributes

**Comment by hank7444** [comment]
it seems valid 
[https://en.wikipedia.org/wiki/JAR_(file_format)](https://en.wikipedia.org/wiki/JAR_(file_format))

**Comment by hank7444** [comment]
## mac chrome
image

## window 7 chrome, it type is empty
image

**Comment by okonet** [comment]
Okay, so it's a browser issue after all. Use an extension pattern as a work around.

**Comment by hank7444** [comment]
OK, I will try it, thx a lot!

**Pull request merged**
