### PR TITLE
Add simple `npm run watch` rule for easier development

### PR DESCRIPTION
**Pull request by mwolson**
**What kind of change does this PR introduce?**

- [ ] bugfix
- [ ] feature
- [ ] refactoring / style
- [X] build / chore
- [ ] documentation

**Did you add tests for your changes?**

- [ ] Yes, my code is well tested
- [X] Not relevant

**If relevant, did you update the documentation?**

- [ ] Yes, I've updated the documentation
- [X] Not relevant

**Summary**

It makes development easier if I can run a file watcher to automatically create builds while working on the project. Webpack comes with a decent one.

**Does this PR introduce a breaking change?**

No

**Other information**

### CODE REVIEW

**Comment by okonet** [comment]
Please check out https://github.com/okonet/react-dropzone/tree/styleguide and let me know what you think.

**Comment by mwolson** [comment]
The styleguide branch seems good so far. Do you want me to target the PR against that branch instead of master?

**Comment by okonet** [comment]
Yes, generally from now on you should submit all docs PRs against it. But I don't think this one is needed since you'll get watch and all nice stuff from react-styleguidist. Right?

**Comment by okonet** [comment]
I'm closing this in favor of `npm start` that will start he styleguide server. #313

**Pull request closed without merging**
