### PR TITLE
fix #159 require 'React' instead of 'react'

### LINKED ISSUE #159: Should require 'react' (lower case)
I'm getting warnings from Webpack when building my project related to dropzone requiring 'React' instead of 'react'.

`There is another module with an equal name when case is ignored.`

### PR DESCRIPTION
**Pull request by j-san**
fix issue `Cannot find module "React"`

https://travis-ci.org/okonet/react-dropzone/builds/120584465#L205

### CODE REVIEW

**Comment by okonet** [comment]
Thanks! :+1:

**Comment by Mistereo** [comment]
It seems to me that this will not work for browsers (without commonjs/requirejs environments).

**Comment by okonet** [comment]
It never was and never will be I think. It just not common for react libs to have React bundled into the dist build. Please use webpack/babelify.

**Comment by j-san** [comment]
You're welcome :smile:

**Pull request merged**
