### PR TITLE
Remove filetype check for preview

### PR DESCRIPTION
**Pull request by zenners**
I used to be able to preview PDFs. This PR seemed simple enough haha

### CODE REVIEW

**Comment by okonet** [comment]
Hmm, it should fail the test but it didn't 🤔

**Comment by okonet** [comment]
This is embarrassing but I forgot to remove `.skip` from the test: https://github.com/okonet/react-dropzone/blob/master/src/index.spec.js#L541

Can you please update the spec file as well so it corresponds this behavior. Also, should this be considered a breaking change?

**Comment by mkuipers** [comment]
>Can you please update the spec file as well so it corresponds this behavior. Also, should this be considered a breaking change?

Doesn't really seem like a breaking change - seems like a bugfix for something that we'd expected to have been caught by the spec failure.

**Comment by okonet** [comment]
I'm closing this in favor of #332

**Pull request closed without merging**
