### PR TITLE
added maxSize and minSize validation #104

### PR DESCRIPTION
**Pull request by lemuelbarango**
fix for file validation #104

### CODE REVIEW

**Comment by okonet** [comment]
That's awesome! Thanks for contributing. To be honest, I think this not be a part of the library but should live in a userland and this lib should allow it by providing a callback. Some users might want size validation but the other part might want to do something more complex or different. This doesn't scale ATM.

My idea was to have a callback function that users can pass along with other props and it should get called in `onDrop` function. I might get some time to work on it soon-ish, but if you feel like it, please go for it!

Does it make sense?

**Comment by prabhu** [comment]
Great PR. I disagree. This should be part of the library. Callback for customising max and min size is frankly an overkill.

**Comment by okonet** [comment]
@lemuelbarango can you please also update the README?

**Comment by lemuelbarango** [comment]
Yeah I can

**Comment by albertkawmi** [comment]
@lemuelbarango @okonet thanks for this. Will this update be published on npm?

**Pull request merged**
