### PR TITLE
Reset orientation onDrop

### PR DESCRIPTION
**Pull request by samlogan**
Prevents images rotating incorrectly on drop

### CODE REVIEW

**Comment by okonet** [comment]
What is this suppose to fix? And why should this be Dropzone's concern? IMO this should live in the userland (ImagePreview component).

**Comment by samlogan** [comment]
I hear you and get your motivation to keep things minimal. However, I am using Dropzone on a recent project and images that were uploaded by a mobile device were rotated incorrectly in the preview, after checking the issue log I found [this](https://github.com/okonet/react-dropzone/issues/147) where you mentioned you would accept a PR that fixes it. Feel free to close this if you feel it is not Dropzone's concern. IMO I would like this to work out of the box.

**Comment by okonet** [comment]
My concern is that it increases the lib size rather significantly for a tiny edge case. https://github.com/blueimp/JavaScript-Load-Image has this solved and probably should be used instead.

**Comment by okonet** [comment]
Another idea could be to implement the image preview component separately and include it as a part of the library.

**Comment by samlogan** [comment]
I like the sound of making the preview a separate component. I can create a new PR with this added

**Comment by okonet** [comment]
Let's try this out and see how it feels.

**Comment by samlogan** [comment]
No stress, will let you know how it goes

**Pull request closed without merging**
