### PR TITLE
Bind this.onDrop to use desired component

### PR DESCRIPTION
**Pull request by seppo0010**

### CODE REVIEW

**Comment by okonet** [comment]
Hey! Thanks for you contribution! You don't need to use `bind` when using `createClass`. You could update the example to use `class`, but even in this case, this would be an anti-pattern. It's much better performance-wise to bind before and use the reference to the bound function in the `render` method to pass it down.

**Comment by seppo0010** [comment]
Uhm, I'm sorry then. I tried this example (with a modification since I was using babel (like in this [example](https://babeljs.io/blog/2015/06/07/react-on-es6-plus)) and it didn't work without the `bind`. What do you recommend me in this case? should I use `bind` or is there another alternative? Thanks

**Comment by okonet** [comment]
You could bind the method in the constructor:

```jsx
class MyComponent extends React.Class {
    constructor() {
        this.onDropCallback = this.onDrop.bind(this);
    }

    onDrop() {
    }
}
```

**Comment by seppo0010** [comment]
Thanks.

**Pull request closed without merging**
